% Analysis of resting state EEG signals from ds004504
% Authors: Natalia López, Julia Reina, Guiomar Niso
% Cajal Institute (CSIC), Madrid, Spain
% December, 2025


clc; clear;



disp("=== My script has started.")

%% Set parameters

% Directory to store brainstorm database (Natalia)
BrainstormDbDir = [pwd, '\brainstorm_db']; % Full path
ReportsDir = 'C:\Users\Proj_AutomaticPipes\EEGdata\out_dir';
DataDir    = 'out_data/';

% Carpeta BIDS con todos los sujetos (Natalia)
BIDS_dir = 'C:\Users\Proj_AutomaticPipes\EEGdata\ds004504-download';

% Protocol name
ProtocolName = 'ds004504_final'; 


%% START BRAINSTORM
disp('== Start Brainstorm defaults');

% Start Brainstorm (no GUI)
brainstorm nogui

% Set Brainstorm database directory
bst_set('BrainstormDbDir',BrainstormDbDir) 
% Reset colormaps
bst_colormaps('RestoreDefaults', 'eeg');

%%%%%%%%
% See Tutorial 1
disp(['- BrainstormDbDir:', bst_get('BrainstormDbDir')]);
disp(['- BrainstormUserDir:', bst_get('BrainstormUserDir')]); % HOME/.brainstorm (operating system)
disp(['- HOME env:', getenv('HOME')]);
disp(['- HOME java:', char(java.lang.System.getProperty('user.home'))]);


%% CREATE PROTOCOL 
disp('== Create protocol');

%%%% SI EL PROTOCOLO EXISTE CAMBIAR NOMBRE
% Create new protocol
UseDefaultAnat = 1; 
UseDefaultChannel = 0;
gui_brainstorm('CreateProtocol', ProtocolName, UseDefaultAnat, UseDefaultChannel);

disp('- New protocol created');

% Start report
bst_report('Start');

%% Import BIDS data
disp('=== Import BIDS dataset')

% Call BIDS import
sFilesAll = bst_process('CallProcess', 'process_import_bids', [], [], ...
    'bidsdir',       {BIDS_dir, 'BIDS'}, ...
    'nvertices',     15000, ...            % number of vertices for cortex surface reconstruction (if FS surfaces available)
    'mni',           'maff8', ...          % method for MNI normalization, if needed
    'anatregister',  'spm12', ...          % method for anatomy registration (if you want registration)
    'groupsessions', 1, ...                % whether to group multiple sessions into one subject
    'channelalign',  1);                   % align sensor positions (if head-shape or fiducials available)

% Verify and report import
if isempty(sFilesAll) == 1
    disp("== Error: no data imported")
else
    disp("== BIDS data successfully imported")
end


%% Loop over participants
for iSub = 1:length(sFilesAll)

    participant = sFilesAll(iSub).SubjectName; % Extract participant information
    disp(['=== Processing participant: ', num2str(participant)]);
    
    % Select participant
    sFilesRaw = sFilesAll(iSub);


%% Quality Control
disp('=== Add EEG positions')

% Process: Add EEG positions
sFilesRaw = bst_process('CallProcess', 'process_channel_addloc', sFilesRaw, [], ...
    'channelfile', {'', ''}, ...
    'usedefault',  'ICBM152: 10-20 19', ...  % ICBM152: 10-20 19
    'fixunits',    1, ...
    'vox2ras',     1, ...
    'mrifile',     {'', ''}, ...
    'fiducials',   []);

disp('=== Compute PSD prior') %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Process: Power spectrum density (Welch)
sFilesPSDpre = bst_process('CallProcess', 'process_psd', sFilesRaw, [], ...
    'timewindow',  [], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', '', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         'Power', ...
         'TimeBands',       [], ...
         'Freqs',           [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFilesPSDpre, [], ...
    'type',           'spectrum', ...  % Frequency spectrum
    'modality',       4, ...  % EEG
    'orient',         1, ...  % left
    'time',           0, ...
    'contact_time',   [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold',      30, ...
    'surfsmooth',     30, ...
    'freq',           0, ...
    'rowname',        '', ...
    'mni',            [0, 0, 0], ...
    'Comment',        '');

disp('=== Quality Control finished')

%% Preprocessing

disp('=== Apply notch and band pass filter')
% Process: Notch filter: 50Hz 60Hz 125Hz 150Hz 187Hz
sFilesNotch = bst_process('CallProcess', 'process_notch', sFilesRaw, [], ...
    'sensortypes', 'EEG', ...
    'freqlist',    [50, 60, 125, 150, 187], ...
    'cutoffW',     2, ...
    'useold',      0, ...
    'read_all',    1);

% Process: High-pass:0.3Hz
sFilesBand = bst_process('CallProcess', 'process_bandpass', sFilesNotch, [], ...
    'sensortypes', 'EEG', ...
    'highpass',    0.3, ...
    'lowpass',     0, ...
    'tranband',    0, ...
    'attenuation', 'strict', ...  % 60dB
    'ver',         '2019', ...  % 2019
    'mirror',      0, ...
    'read_all',    1);


disp('=== Apply montage')
% Process: Apply montage
sFilesEEG = bst_process('CallProcess', 'process_montage_apply', sFilesBand, [], ...
    'montage',    'Average reference', ...
    'usectfcomp', 1, ...
    'usessp',     1);

disp('=== Preprocessing finished')

disp('=== Detect blinks and apply SSP')
% Process: Detect eye blinks
bst_process('CallProcess', 'process_evt_detect_eog', sFilesEEG, [], ...
    'channelname', 'Fp1', ...
    'timewindow',  [], ...
    'eventname',   'blink');

% Process: SSP EOG: blink
bst_process('CallProcess', 'process_ssp_eog', sFilesEEG, [], ...
    'eventname',   'blink', ...
    'sensortypes', 'EEG', ...
    'usessp',      1, ...
    'select',      1);

% Process: Snapshot: SSP projectors
bst_process('CallProcess', 'process_snapshot', sFilesEEG, [], ...
    'type',           'ssp', ...  % SSP projectors
    'modality',       4, ...  % EEG
    'orient',         1, ...  % left
    'time',           0, ...
    'contact_time',   [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold',      30, ...
    'surfsmooth',     30, ...
    'freq',           0, ...
    'rowname',        '', ...
    'mni',            [0, 0, 0], ...
    'Comment',        '');

%% PSD post processing

disp('=== Compute PSD post')
% Process: Power spectrum density (Welch)
sFilesPSDpost = bst_process('CallProcess', 'process_psd', sFilesEEG, [], ...
    'timewindow',  [], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', '', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         'Power', ...
         'TimeBands',       [], ...
         'Freqs',           [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFilesPSDpost, [], ...
    'type',           'spectrum', ...  % Frequency spectrum
    'modality',       4, ...  % EEG
    'orient',         1, ...  % left
    'time',           0, ...
    'contact_time',   [0, 0.1], ...
    'contact_nimage', 12, ...
    'threshold',      30, ...
    'surfsmooth',     30, ...
    'freq',           0, ...
    'rowname',        '', ...
    'mni',            [0, 0, 0], ...
    'Comment',        '');


%% Compute sources

disp('=== Compute head model') %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Process: Compute head model
sFilesHead = bst_process('CallProcess', 'process_headmodel', sFilesEEG, [], ...
    'Comment',     '', ...
    'sourcespace', 1, ...  % Cortex surface
    'meg',         3, ...  % Overlapping spheres
    'eeg',         2, ...  % OpenMEEG BEM
    'ecog',        2, ...  % OpenMEEG BEM
    'seeg',        2, ...  % OpenMEEG BEM
    'nirs',        1, ...  % 
    'openmeeg',    struct(...
         'BemSelect',    [1, 1, 1], ...
         'BemCond',      [1, 0.0125, 1], ...
         'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
         'BemFiles',     {{}}, ...
         'isAdjoint',    0, ...
         'isAdaptative', 1, ...
         'isSplit',      0, ...
         'SplitLength',  4000), ...
    'nirstorm',    struct(...
         'FluenceFolder',    'https://neuroimage.usc.edu/resources/nst_data/fluence/', ...
         'smoothing_method', 'geodesic_dist', ...
         'smoothing_fwhm',   10), ...
    'channelfile', '');

disp('=== Compute noise covariance matrix')
% Process: Compute covariance (noise or data)
sFilesNoise = bst_process('CallProcess', 'process_noisecov', sFilesEEG, [], ...
    'baseline',       [], ...
    'datatimewindow', [], ...
    'sensortypes',    'EEG', ...
    'target',         1, ...  % Noise covariance     (covariance over baseline time window)
    'dcoffset',       1, ...  % Block by block, to avoid effects of slow shifts in data
    'identity',       1, ...
    'copycond',       0, ...
    'copysubj',       0, ...
    'copymatch',      0, ...
    'replacefile',    1);  % Replace


disp('=== Compute sources')
% Process: Compute sources [2018]
sFilesSources = bst_process('CallProcess', 'process_inverse_2018', sFilesEEG, [], ...
    'output',  1, ...  % Kernel only: shared
    'inverse', struct(...
         'Comment',        'MN: EEG', ...
         'InverseMethod',  'minnorm', ...
         'InverseMeasure', 'amplitude', ...
         'SourceOrient',   {{'fixed'}}, ...
         'Loose',          0.2, ...
         'UseDepth',       1, ...
         'WeightExp',      0.5, ...
         'WeightLimit',    10, ...
         'NoiseMethod',    'reg', ...
         'NoiseReg',       0.1, ...
         'SnrMethod',      'fixed', ...
         'SnrRms',         1e-06, ...
         'SnrFixed',       3, ...
         'ComputeKernel',  1, ...
         'DataTypes',      {{'EEG'}}));


disp('=== Finished computing sources')

% Analysis of resting state data

disp('=== Separate in frequency bands')
% Process: Power spectrum density (Welch), divide into frequency bands
sFilesSourceBands = bst_process('CallProcess', 'process_psd', sFilesSources, [], ...
    'timewindow',  [], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'units',       'physical', ...  % Physical: U2/Hz
    'sensortypes', '', ...
    'win_std',     0, ...
    'edit',        struct(...
         'Comment',         'Power,FreqBands', ...
         'TimeBands',       [], ...
         'Freqs',           {{'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'; 'gamma2', '60, 90', 'mean'}}, ...
         'ClusterFuncTime', 'none', ...
         'Measure',         'power', ...
         'Output',          'all', ...
         'SaveKernel',      0));

% Process: Spectrum normalization
sFilesNorm = bst_process('CallProcess', 'process_tf_norm', sFilesSourceBands, [], ...
    'normalize', 'relative2020', ...  % Relative power (divide by total power)
    'overwrite', 0);

%%%%%%%%%%%% Add tag "total" al sFilesBands

% Process: Spatial smoothing (3.00 mm)
sFilesSmooth = bst_process('CallProcess', 'process_ssmooth_surfstat', sFilesNorm, [], ...
    'fwhm',      3, ...
    'method',    'fixed_fwhm', ...  % Fixed FWHM for all surfaces
    'overwrite', 0);


disp('=== Finished analysis of resting state on sources')


%% Save report and delete protocol

% Save report
disp('=== Save report');
ReportName = sprintf('Subject %d', iSub);
ReportFile = bst_report('Save', num2str(participant), []);
bst_report('Export', ReportFile, ReportsDir);

% % % % % Copy brainstorm_db data
% % % % copyfile([BrainstormDbDir,'/',ProtocolName], DataDir);
% % % % 
% % % % % Delete existing protocol
% % % % gui_brainstorm('DeleteProtocol', ProtocolName);
% % % % disp('== Delete protocol');

end

%% DONE
disp('=== Done!');
